repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.239'
    hooks:
      - id: ruff
        args: ["--ignore", "E712,E501,F541,E711,E713,E731,F403,F405,E722,E402", "--line-length" , "160" ,"--extend-select", "I", "--fix"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
#
#   - repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#       - id: isort
